version: 2.1

orbs:
  golangci-lint: timakin/golangci-lint@0.1.1

executors:
  default:
    docker:
      - image: golang:1.12

workflows:
  ci:
    jobs:
      - golangci-lint/lint:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - test:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
          requires:
            - golangci-lint/lint
            - test

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install gotest
          command: go get -u github.com/rakyll/gotest
      - run:
          name: Run Tests
          command: gotest -v ./...
  release:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: GoRelease
          command: curl -sL https://git.io/goreleaser | bash
